# Generated by Django 4.2.3 on 2023-07-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='type_document',
            field=models.CharField(choices=[('Surat Kuasa', 'Surat Kuasa'), ('Surat Gugatan', 'Surat Gugatan'), ('Surat Perjanjian', 'Surat Perjanjian'), ('Kontrak Kerja', 'Kontrak Kerja')], default='Surat Kuasa', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
