# Generated by Django 4.2.3 on 2023-07-07 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_document_price_document_type_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Surat Kuasa', 'Surat Kuasa'), ('Surat Gugatan', 'Surat Gugatan'), ('Surat Perjanjian', 'Surat Perjanjian'), ('Kontrak Kerja', 'Kontrak Kerja')], default='Surat Kuasa', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='type_document',
        ),
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='document.typedocument'),
        ),
    ]
