# Generated by Django 4.1.4 on 2023-07-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_lawyer_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='group',
            field=models.CharField(blank=True, default='Lawyer', max_length=100, null=True),
        ),
    ]
