# Generated by Django 4.1.4 on 2023-07-06 15:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0004_alter_lawyer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='price',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='time',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='user',
        ),
        migrations.AddField(
            model_name='consultation',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('duration', models.IntegerField(blank=True, default=0, help_text='Duration in minutes', null=True)),
                ('type', models.CharField(blank=True, default='Chat', help_text='Type of consultation', max_length=100, null=True)),
                ('price', models.IntegerField(default=0)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='consultation.consultation')),
            ],
        ),
    ]
