# Generated by Django 4.1.4 on 2023-07-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0005_remove_consultation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
