# Generated by Django 4.1.4 on 2023-07-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0006_alter_variation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='type',
            field=models.CharField(blank=True, choices=[('Chat', 'Chat'), ('Call', 'Call'), ('Meet', 'Meet')], max_length=10, null=True),
        ),
    ]
