# Generated by Django 4.1.4 on 2023-07-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0007_alter_variation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='image',
            field=models.ImageField(blank=True, default='lawyer/images/default.jpg', null=True, upload_to='lawyer/images'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='duration',
            field=models.PositiveIntegerField(blank=True, choices=[(15, '15 minutes'), (30, '30 minutes'), (45, '45 minutes'), (60, '1 hour')], null=True),
        ),
    ]
