# Generated by Django 4.2.3 on 2023-07-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='variation_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='variation_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
