# Generated by Django 4.2.3 on 2023-07-07 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_alter_document_document'),
        ('order', '0004_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='document.document'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='variation_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='variation_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
