# Generated by Django 4.2.3 on 2023-07-07 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0008_alter_lawyer_image_alter_variation_duration'),
        ('order', '0005_cart_document_alter_cart_variation_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='consultation.consultation'),
        ),
    ]
