# Generated by Django 4.2.3 on 2023-07-08 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0008_alter_lawyer_image_alter_variation_duration'),
        ('order', '0006_alter_cart_consultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='consultation.consultation'),
        ),
    ]
